[package]
name = "med-man-sports-video-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"

[build-dependencies]
bindgen = "0.69.1"
